nodeLinker: pnp

npmScopes:
  echoscript:
    npmAlwaysAuth: true
    npmAuthToken: '${ECHOSCRIPT_NPM_TOKEN}'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: packages/plugin/plugin/bundle.js
    spec: 'yarn-plugin-echoscript'

yarnPath: .yarn/releases/yarn-3.6.3.cjs
