compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmPreapprovedPackages: eslint-config-taeyoon

npmScopes:
  echoscript:
    npmAlwaysAuth: true
    npmAuthToken: "${ECHOSCRIPT_NPM_TOKEN:-}"

plugins:
  - path: packages/plugin/plugin/bundle.js
    spec: yarn-plugin-echoscript
