compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  echoscript:
    npmAlwaysAuth: true
    npmAuthToken: "${ECHOSCRIPT_NPM_TOKEN:-}"

plugins:
  - path: packages/plugin/plugin/bundle.js
    spec: yarn-plugin-echoscript

yarnPath: .yarn/releases/yarn-4.13.0.cjs
