compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmPreapprovedPackages: eslint-config-taeyoon

packageExtensions:
  eslint-config-taeyoon@*:
    dependencies:
      typescript: "*"

npmScopes:
  echoscript:
    npmAlwaysAuth: true
    npmAuthToken: "${ECHOSCRIPT_NPM_TOKEN:-}"

plugins:
  - path: packages/plugin/plugin/bundle.js
    spec: yarn-plugin-echoscript

yarnPath: .yarn/releases/yarn-4.16.0.cjs
